### ISSUE TITLE
Unexpected effect of inheritance on verification

### ISSUE THREAD

**Issue by OlivierBlanvillain** [epfl-lara/stainless#39] opened 2017-05-26 09:24 UTC
I have minimised an example where slightly changing inheritance affect verification in unexpected ways. I'm using 3 level of inheritance:

```scala
trait A            { def f(i: Int): Int }
class B extends A  { def f(i: Int): Int = i + 1 }
class C extends B  { def proof: Boolean = ... }
```

The proof I wrote is `class C` is able to verify when I change `class B extends A {...}` to `trait B {...}`. There might be two issues in one, because the verification also fails if using `class C {...}` instead of `trait B {...}`. This is the complete example:

```scala
trait Monad[F[_]] {
  def pure[A](x: A): F[A]
  def flatMap[A, B](fa: F[A])(f: A => F[B]): F[B]
}
```

```scala
import stainless.collection._

// Doesn't work with:
// class ListMonadInstance extends Monad[List] {

// Neither with
// class ListMonadInstance {

// But it does this way:
trait ListMonadInstance {
  def pure[A](x: A): List[A] = List(x)

  def flatMap[A, B](fa: List[A])(f: A => List[B]): List[B] =
    fa match {
      case Cons(x, xs) => combine(f(x), flatMap(xs)(f))
      case Nil() => Nil()
    }

  def combine[A](l1: List[A], l2: List[A]): List[A] =
    l1 match {
      case Cons(x, xs) => Cons(x, combine(xs, l2))
      case Nil() => l2
    }
}
```

```scala
import stainless.collection._
import stainless.lang._
import stainless.proof._

class ListMonadProofs extends ListMonadInstance {
  def monadAssociativity[A, B, C](fa: List[A], f: A => List[B], g: B => List[C]) =
    (flatMap(flatMap(fa)(f))(g) == flatMap(fa)(x => flatMap(f(x))(g)))

  def monadAssociativityProof[A, B, C](
    fa: List[A],
    fb: List[B],
    fc: List[C],
    f: A => List[B],
    g: B => List[C]
  ): Boolean = {
    monadAssociativity(fa, f, g) because {
      (  combine(combine(fc, flatMap(fb)(g)), flatMap(fa)(x => flatMap(f(x))(g)))
      == combine(fc, flatMap(combine(fb, flatMap(fa)(f)))(g))) because {
        fc match {
          case Cons(_, xs) =>
            monadAssociativityProof(fa, fb, xs, f, g)
          case Nil() => fb match {
            case Cons(x, xs) =>
              monadAssociativityProof(fa, xs, g(x), f, g)
            case Nil() => fa match {
              case Cons(x, xs) => monadAssociativityProof(xs, f(x), Nil(), f, g)
              case Nil() => true
            }
          }
        }
      }
    }
  }.holds
}
```

**Comment by OlivierBlanvillain** [comment] 2017-05-26 09:43
Another discovery: adding the following to the above example also breaks verification:

```scala
class TotallyUnrelatedUnusedAnywere extends ListMonadInstance
```

**Comment by romac** [comment] 2018-05-31 12:14
Closing as I cannot reproduce this issue anymore. [This gist](https://gist.github.com/romac/0c3b49fcbd811aee839bedf24b70a9f0) now seems to verify just fine.

Feel free to re-open if I missed anything.

**Closed by romac** 2018-05-31 12:14 UTC
