### ISSUE TITLE
Line number missing for verification condition about cast correctness

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#210] opened 2018-03-29 08:45 UTC
```scala
object O {
  case class A() 

  abstract class C {
    val startPos: A = A()
  }
}
```

```
[  Info  ]   ┌──────────────────────┐
[  Info  ] ╔═╡ verification summary ╞═══════════════════════════════════════════════════════════════════╗
[  Info  ] ║ └──────────────────────┘                                                                   ║
[  Info  ] ║ startPos       cast correctness           valid from cache              ?:?:?     0,001    ║
[  Info  ] ╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
[  Info  ] ║ total: 1    valid: 1    (1 from cache) invalid: 0    unknown: 0    time:   0,001           ║
[  Info  ] ╚════════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by samarion** [comment] 2018-03-29 13:18
I can't reproduce with the latest Stainless, so I'll hope it's fixed and close it :)

**Closed by samarion** 2018-03-29 13:18 UTC
Labels: reporting

**Comment by jad-hamza** [comment] 2018-03-29 13:27
Oh that's odd, I still have the `?:?:?`

**Comment by samarion** [comment] 2018-03-29 13:31
I don't even see the "cast correctness" VC. Maybe it's because I'm running against a later version of Inox. Anyway there seem to be many places where positions are not copied in `TypeEncoding` so I'm covering the main cases.
