### ISSUE TITLE
stainless cannot recover from missing dependencies (triggered by parameter initializers).

### ISSUE THREAD

**Issue by saraswat** [epfl-lara/stainless#749] opened 2020-05-25 22:59 UTC
Given the small code file:
```
import stainless.lang._
import stainless.collection._
import stainless.annotation._

object verified {

 case class Stuff(x: List[BigInt] = Nil(), y: List[BigInt] = Nil())

  val empty_book = Stuff()
}
```

`stainless` barfs with:
```
sbt:stainless_test> verified/run
[info] Compiling 30 Scala sources to /Users/vijaysaraswat/stainless_test/verified/target/scala-2.12/classes ...
[error] empty_book$0 depends on missing dependencies: apply$default$1$0, apply$default$2$0.
[error] Cannot recover from missing dependencies
[error] ## Exception when compiling 30 sources to /Users/vijaysaraswat/stainless_test/verified/target/scala-2.12/classes
[error] inox.package$FatalError: Cannot recover from missing dependencies
[error] inox.Reporter.onFatal(Reporter.scala:39)
[error] inox.Reporter.fatalError(Reporter.scala:50)
[error] inox.Reporter.fatalError(Reporter.scala:98)
[error] stainless.frontend.Recovery$.recover(Recovery.scala:110)
[error] stainless.frontend.SplitCallBack.processFunction(SplitCallBack.scala:149)
[error] stainless.frontend.SplitCallBack.$anonfun$processSymbols$3(SplitCallBack.scala:138)
[error] stainless.frontend.SplitCallBack.$anonfun$processSymbols$3$adapted(SplitCallBack.scala:137)
[error] scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[error] scala.collection.Iterator.foreach(Iterator.scala:941)
[error] scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:181)
[error] scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[error] stainless.frontend.SplitCallBack.processSymbols(SplitCallBack.scala:137)
[error] stainless.frontend.SplitCallBack.endExtractions(SplitCallBack.scala:67)
[error] stainless.frontends.scalac.StainlessPluginComponent.onRun(StainlessPlugin.scala:114)
...
```

**Comment by romac** [comment] 2020-05-26 06:58
Yes, default parameter initializers for classes are currently not supported (though they are for functions). Until we do so, we should indeed improve the error message that's reported.

**Comment by samarion** [comment] 2020-06-04 14:54
I think scalac does most of the legwork for default parameters. Adding support for case class default parameters probably just implies copying over the relevant code from function extraction.

**Comment by vkuncak** [comment] 2020-06-13 21:24
Possibly a duplicate of #481

**Closed** 2023-04-25 14:13 UTC
Labels: reporting, feature, doable
