### ISSUE TITLE
Weird forall behavior

### ISSUE THREAD

**Issue by BLepers** [epfl-lara/stainless#58] opened 2017-07-10 14:10 UTC
```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {
   case class SchedEntity(val id:BigInt, val state: BigInt, val quanta: BigInt, val core:BigInt, val load: BigInt, val rq:List[BigInt]);

   case class Core(val current: Option[BigInt], val ready: BigInt);
   case class SharedState(
      val progress:BigInt,
      val cores:List[BigInt],
      val states:BigInt => Core,
      val entities:BigInt => SchedEntity) {
         require(forall((id:BigInt) => entities(id).rq.forall(e => entities(e).id < id && entities(e).id >= 0)))
   }

   def test(s:SharedState, id:BigInt):Boolean = {
      s.entities(id).rq.forall(e => s.entities(e).id < s.entities(id).id && s.entities(e).id >= 0)
   }.holds;
```

Stainless is not able to verify the function "test". Is there any reason for that? (It looks like the property of the forall should trivially apply there?)

Error is:
```
[  Info  ]  - Now considering 'postcondition' VC for test @22:7...
[ Error  ] Quantification forall[BigInt](x$246.entities.f(x$201).rq, fun1[BigInt, Boolean]((x$205: BigInt) => x$245.entities.f(x$205).id < x$201 && x$247.entities.f(x$205).id >= x$249, x$248)) does not fit in supported fragment.
[ Error  ]   Reason: Unandled implications from operation x$246.entities.f(x$201).rq
[ Error  ] Model obtained was:
[ Error  ]   id: BigInt     -> 14133
[ Error  ]   s: SharedState -> SharedState(8, Nil[BigInt](), (x$201: BigInt) => Core(None[BigInt](), 0), (x$331: BigInt) => if (x$331 == 14131) {
[ Error  ]     SchedEntity(7145, 21, 22, 23, 24, Nil[BigInt]())
[ Error  ]   } else if (x$331 == 14139) {
[ Error  ]     SchedEntity(14137, 39, 40, 41, 42, Nil[BigInt]())
[ Error  ]   } else if (x$331 == 5874) {
[ Error  ]     SchedEntity(-1, 33, 34, 35, 36, Nil[BigInt]())
[ Error  ]   } else if (x$331 == 14130) {
[ Error  ]     SchedEntity(14466, 28, 29, 30, 31, Nil[BigInt]())
[ Error  ]   } else if (x$331 == 14138) {
[ Error  ]     SchedEntity(14137, 15, 16, 17, 18, Cons[BigInt](14139, Nil[BigInt]()))
[ Error  ]   } else if (x$331 == 14133) {
[ Error  ]     SchedEntity(5875, 78, 79, 80, 81, Cons[BigInt](14131, Nil[BigInt]()))
[ Error  ]   } else if (true) {
[ Error  ]     SchedEntity(14137, 15, 16, 17, 18, Cons[BigInt](14139, Nil[BigInt]()))
[ Error  ]   } else {
[ Error  ]     SchedEntity(14137, 15, 16, 17, 18, Cons[BigInt](14139, Nil[BigInt]()))
[ Error  ]   })
[Warning ]  => UNKNOWN
```

**Comment by samarion** [comment] 2017-07-10 14:30
Hmm, it seems to me that Stainless knows that

entities(id).rq.forall(e => entities(e).id < id && entities(e).id >= 0)

but you're trying to show that

entities(id).rq.forall(e => entities(e).id < entities(id).id &&
entities(e).id >= 0)

so the properties don't quite match up.


As a site note, in general it doesn't play out so well in Stainless to
mix quantifiers with list.forall, because the instantiation algorithm
sees the lambda passed to list.forall as a black box and can't do
unification. We should experiment with adding a postcondition to
list.forall stating that forall(e => (list.content contains e) ==>
p(e)). I'll need to run a few checks to make sure the quantifier
simplifier then inlines the postcondition correctly. In the mean time,
it's probably best to use forall(e => (list.content contains e) ==>
p(e)) instead of list.forall.

**Comment by BLepers** [comment] 2017-07-10 15:17
Indeed, my bad... :/ The "correct" version doesn't verify either:

```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {
   case class SchedEntity(val id:BigInt, val state: BigInt, val quanta: BigInt, val core:BigInt, val load: BigInt, val rq:List[BigInt]);

   case class Core(val current: Option[BigInt], val ready: BigInt);
   case class SharedState(
      val progress:BigInt,
      val cores:List[BigInt],
      val states:BigInt => Core,
      val entities:BigInt => SchedEntity) {
         require(forall((id:BigInt) => entities(id).rq.forall(e => entities(e).id < entities(id).id && entities(e).id >= 0)))
   }

   def test(s:SharedState, id:BigInt):Boolean = {
      s.entities(id).rq.forall(e => s.entities(e).id < s.entities(id).id && s.entities(e).id >= 0)
   }.holds;
}
```

Thanks for the precision on the quantifiers. I assumed that this code would verify since the code in https://github.com/epfl-lara/stainless/issues/56 verifies (both look very similar to me, but maybe they are fundamental differences in the way the solver reasons about them). :)

**Comment by samarion** [comment] 2017-07-10 15:22
I'll run some checks on this, it seems to me that this particular instance
should verify. However my comment about not mixing foralls still holds in
general.

**Comment by jad-hamza** [comment] 2017-07-10 20:06
You can try to wrap the expressions inside forall quantifiers into functions, it often helps

```scala
import stainless.collection._
import stainless.lang._

object DataRacing {

  def goodEntity(entities: BigInt => SchedEntity, id: BigInt): Boolean = {
     entities(id).rq.forall(e => entities(e).id < entities(id).id && entities(e).id >= 0)
  }

  case class SchedEntity(val id:BigInt, val rq:List[BigInt])
   
  case class SharedState(val entities:BigInt => SchedEntity) {
    require(forall((id:BigInt) => goodEntity(entities, id)))
  }

  def test(s:SharedState, id:BigInt):Boolean = {
    goodEntity(s.entities, id)
  }.holds;
}
```

**Comment by BLepers** [comment] 2017-07-11 07:42
Thanks for the answers!

**Comment by BLepers** [comment] 2017-07-11 08:16
```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {
   case class SchedEntity(val id:BigInt, val state: BigInt, val quanta: BigInt, val core:BigInt, val load: BigInt, val rq:List[BigInt]);

   def goodEntity(entities: BigInt => SchedEntity, id: BigInt): Boolean = {
      //entities(id).rq.forall(e => entities(e).id < entities(id).id && entities(e).id >= 0)
      forall((e:BigInt) => (entities(id).rq.content contains e) ==> (entities(e).id < entities(id).id && entities(e).id >= 0))
   }

   case class Core(val current: Option[BigInt], val ready: BigInt);
   case class SharedState(
      val progress:BigInt,
      val cores:List[BigInt],
      val states:BigInt => Core,
      val entities:BigInt => SchedEntity) {
         require(forall((id:BigInt) => goodEntity(entities, id)))
   }

   @induct
   def flatten(s:SharedState, rq:List[BigInt], id:BigInt):List[BigInt] = {
      require(goodEntity(s.entities, id) && id >= 0)
      decreases(id, rq.size)
      rq match {
         case Nil() => Nil()
         case Cons(t, ts) =>
            val sched = s.entities(t)
            flatten(s, sched.rq, sched.id) ++ flatten(s, ts, id)
      }
   }
}
```


I'm still a bit confused on why this doesn't verify. Error is:

```
[ Error  ] Quantification x$193 ∉ content[BigInt](x$204) || x$208.f(x$193).id < x$205 && x$207.f(x$193).id >= x$206 does not fit in supported fragment.
[ Error  ]   Reason: Unandled implications from operation x$208.f(x$193).id
```
or

```
[ Error  ] Quantification goodEntity(x$218, x$202) does not fit in supported fragment.
[ Error  ]   Reason: Can't guarantee model for complex matchers.
```

when I use list.forall. Any hint on what these errors mean?

I can always try to rewrite things as in https://github.com/epfl-lara/stainless/issues/56, which verifies, but I'm not sure to get the difference (is it the extra indirection via the entities() function call?).

Thanks! :)

**Comment by BLepers** [comment] 2017-07-11 08:44
Simpler example:


Verifies:
```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {
   case class SharedState(val rqs:BigInt => List[BigInt]) {
      require(forall((id:BigInt) => rqs(id).forall(e => e < id && e >= 0)))
   }

   @induct
   def isTree(s:SharedState, content:List[BigInt], id:BigInt):Boolean = {
      require(content.forall(e => e < id && e >= 0) && id >= 0)
      decreases(id, content.size)


      content match {
         case Nil() => true
         case Cons(t, ts) =>
            isTree(s, ts, id) && isTree(s, s.rqs(t), t)
      }
   }
}
```

Does not verify:
```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {
   case class SharedState(val ids:BigInt => BigInt, val rqs:BigInt => List[BigInt]) {
      require(forall((id:BigInt) => rqs(id).forall(e => ids(e) < ids(id) && ids(e) >= 0)))
   }

   @induct
   def isTree(s:SharedState, content:List[BigInt], id:BigInt):Boolean = {
      require(content.forall(e => s.ids(e) < s.ids(id) && s.ids(e) >= 0) && id >= 0)
      decreases(id, content.size)


      content match {
         case Nil() => true
         case Cons(t, ts) =>
            isTree(s, ts, id) && isTree(s, s.rqs(t), s.ids(t))
      }
   }
}
```

Is there a way to understand the fundamental difference from the solver point of view? :)

**Comment by jad-hamza** [comment] 2017-07-11 09:11
You can try running with --checkmodels, this verifies that the counter-example found is really a counter-example. Sometimes you get lucky, and you get INVALID instead of UNKNOWN. In your code above, there seems to be a problem, does sched.id >= 0 always hold?

I made a few changes to the code. First I would wrap the expression under the forall into another named function (`goodRq`, sorry for the bad names!). Then the precondition `goodEntity(s.entities, id)` seems to be redundant with the invariant of s: SharedState (you can assert this expression when you wish). Finally I don't think you need the induct annotation when you're doing the induction manually.

```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {
   case class SchedEntity(val id:BigInt, val rq:List[BigInt]);

   def goodRq(entities: BigInt => SchedEntity, id: BigInt, e: BigInt) = {
      (entities(id).rq.content contains e) ==> (entities(e).id < entities(id).id && entities(e).id >= 0)
   }
   
   def goodEntity(entities: BigInt => SchedEntity, id: BigInt): Boolean = {
      //entities(id).rq.forall(e => entities(e).id < entities(id).id && entities(e).id >= 0)
      forall((e:BigInt) => goodRq(entities, id, e))
   }

   case class Core(val current: Option[BigInt], val ready: BigInt);
   case class SharedState(val entities:BigInt => SchedEntity) {
      require(forall((id:BigInt) => goodEntity(entities, id)))
   }

//    @induct
   def flatten(s:SharedState, rq:List[BigInt], id:BigInt):List[BigInt] = {
      require(id >= 0)
      decreases(id, rq.size)
      rq match {
         case Nil() => Nil()
         case Cons(t, ts) =>
            val sched = s.entities(t)
            assert(sched.id >= 0)
            flatten(s, sched.rq, sched.id) ++ flatten(s, ts, id)
      }
   }
}
```

```
[  Info  ]  - Now considering 'body assertion' VC for flatten @34:13...
[ Debug  ] (id >= 0 && (id, size[BigInt](rq))._1 >= 0 && (id, size[BigInt](rq))._2 >= 0 && ¬rq.isInstanceOf[Nil[BigInt]] && rq.isInstanceOf[Cons[BigInt]]) ==> {
[ Debug  ]   val t: BigInt = rq.asInstanceOf[Cons[BigInt]].h
[ Debug  ]   val ts: List[BigInt] = rq.asInstanceOf[Cons[BigInt]].t
[ Debug  ]   val sched: SchedEntity = s.entities(t)
[ Debug  ]   sched.id >= 0
[ Debug  ] }
[ Debug  ] Solving with: nativez3
[Warning ]  => INVALID
[Warning ] Found counter-example:
[Warning ]   id: BigInt       -> 0
[Warning ]   s: SharedState   -> SharedState((x$217: BigInt) => if (x$217 == 3) {
[Warning ]     SchedEntity(-1, Nil[BigInt]())
[Warning ]   } else if (x$217 == 15) {
[Warning ]     SchedEntity(0, Nil[BigInt]())
[Warning ]   } else if (true) {
[Warning ]     SchedEntity(-1, Nil[BigInt]())
[Warning ]   } else {
[Warning ]     SchedEntity(-1, Nil[BigInt]())
[Warning ]   })
[Warning ]   rq: List[BigInt] -> Cons[BigInt](3, Cons[BigInt](12, Nil[BigInt]()))
```

I think the problem is that the rq you are inducting on is not the rq of any SchedEntity.

**Comment by jad-hamza** [comment] 2017-07-11 09:43
About the simpler examples you gave, it looks like there is a mismatch in the ids. I refactored the code by naming the expression, the assert `goodId(s.ids, s.rqs(s.ids(t)), s.ids(t))` verifies correctly, but what you need is `goodId(s.ids, s.rqs(t), s.ids(t))`. 

```scala
import stainless.lang._
import stainless.util.Random
import stainless.collection._
import stainless.lang._
import scala.Any
import stainless.annotation._
import stainless.proof._

object DataRacing {

   def inRange(ids: BigInt => BigInt, id: BigInt, e: BigInt) = {
      ids(e) < ids(id) && ids(e) >= 0
   }  
  
   def goodId(ids: BigInt => BigInt, l: List[BigInt], id: BigInt) = {
      l.forall(e => inRange(ids, id, e))
   }

   case class SharedState(val ids:BigInt => BigInt, val rqs:BigInt => List[BigInt]) {
      require(forall((id:BigInt) => goodId(ids, rqs(id), id)))
   }

//    @induct
   def isTree(s:SharedState, content:List[BigInt], id:BigInt):Boolean = {
      require(goodId(s.ids, content, id) && id >= 0)
//       require(content.forall(e => inRange(s.ids, id, e)) && id >= 0)
      decreases(id, content.size)


      content match {
         case Nil() => true
         case Cons(t, ts) =>
            assert(s.ids(t) >= 0)
            assert(inRange(s.ids, id, t))
            assert(forall((idx: BigInt) => goodId(s.ids, s.rqs(idx), idx)))
            assert(goodId(s.ids, s.rqs(s.ids(t)), s.ids(t)))
            assert(goodId(s.ids, s.rqs(t), s.ids(t)))
            isTree(s, ts, id) && isTree(s, s.rqs(t), s.ids(t))
      }
   }
}
```

I don't think this is related, but there is also an issue with preconditions in `goodId`. @samarion do you know why? Do we have to add in `goodId` a precondition that talks about the precondition of `ids`?

**Comment by BLepers** [comment] 2017-07-11 09:45
Yes, indeed, I was trying to fix the id mess... :/ (I got slightly confused by my data structures...)

Thanks for the fix.

**Comment by samarion** [comment] 2017-07-20 20:24
Fixed in https://github.com/epfl-lara/inox/commit/348727de0bd69c5a52df68fd61c6797f66a98bce

**Closed by samarion** 2017-07-20 20:24 UTC
