### ISSUE TITLE
Problem with VC cache, invalid stream header

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#330] opened 2018-09-17 14:40 UTC
In `frontends/benchmarks/verification/valid`, running `stainless-scalac` on `ConcRope.scala` leads to an `invalid stream header` error (if you don't get the error the first time, run it a second time as the problem comes from the vc-cache).

```
$ stainless-scalac ConcRope.scala 
[  Info  ]  - Checking cache: 'match exhaustiveness' VC for concInv @41:28...
[  Info  ] Cache miss: 'match exhaustiveness' VC for concInv @41:28...
[  Info  ]  - Now solving 'match exhaustiveness' VC for concInv @41:28...
[  Info  ]  - Checking cache: 'match exhaustiveness' VC for balanced @50:7...
[  Info  ] Cache miss: 'match exhaustiveness' VC for balanced @50:7...
[  Info  ]  - Now solving 'match exhaustiveness' VC for balanced @50:7...
[  Info  ]  - Checking cache: 'match exhaustiveness' VC for isLeaf @21:7...
[  Info  ] Cache miss: 'match exhaustiveness' VC for isLeaf @21:7...
[  Info  ]  - Now solving 'match exhaustiveness' VC for isLeaf @21:7...
[  Info  ]  - Result for 'match exhaustiveness' VC for balanced @50:7:
[  Info  ]  => VALID
[  Info  ]  - Result for 'match exhaustiveness' VC for isLeaf @21:7:
[  Info  ]  => VALID
[  Info  ]  - Result for 'match exhaustiveness' VC for concInv @41:28:
[  Info  ]  => VALID
[ Error  ] error: invalid stream header: 05ACED00
[  Info  ]   ┌───────────────────┐
[  Info  ] ╔═╡ stainless summary ╞══════════════════════════════════════════════════════════════════════╗
[  Info  ] ║ └───────────────────┘                                                                      ║
[  Info  ] ║ balanced    match exhaustiveness      valid   nativez3    ConcRope.scala:50:7       0,284  ║
[  Info  ] ║ concInv     match exhaustiveness      valid   nativez3    ConcRope.scala:41:28      0,452  ║
[  Info  ] ║ isLeaf      match exhaustiveness      valid   nativez3    ConcRope.scala:21:7       0,121  ║
[  Info  ] ╟┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╢
[  Info  ] ║ total: 3    valid: 3    (0 from cache) invalid: 0    unknown: 0    time:   0,857           ║
[  Info  ] ╚════════════════════════════════════════════════════════════════════════════════════════════╝
[  Info  ] Shutting down executor service.
```

**Comment by samarion** [comment] 2018-09-18 05:55
Hmm, I can't reproduce this. Are you on latest Stainless with a deleted cache?

**Comment by samarion** [comment] 2018-10-01 06:13
Should be fixed by https://github.com/epfl-lara/stainless/commit/16b8a8d6cfac4bf619f8e14ee55849e0bcb2af2e

**Closed by samarion** 2018-10-01 06:13 UTC

**Comment by jad-hamza** [comment] 2018-10-01 08:12
Yes, thanks!
