### ISSUE TITLE
Consistency problems with imperative features

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/stainless#143] opened 2017-12-14 13:25 UTC
There are some strange interactions between imperative features and the class system and their invariants. This is an example inspired from "Intersection Types and Computational Effects". Thanks to @romac for helping me set this up.

The first issue is that n.load(-1) is discarded, and Stainless therefore considers that n is still equal to 0 after the load. Is it because n.load(-1) is considered pure due to the nesting of the var inside `Container`?

```scala
object Imperative {
  case class Container(var v: BigInt) {
    def load(x: BigInt) = {
      v = x
    }
  }

  abstract class Box {
    val c = Container(0)
    def load(x: BigInt) = c.load(x)
  }

  case class Nat() extends Box {
    require(c.v >= 0)         // should not be allowed (?)
    
    def extract(): BigInt = {
      c.v
    } ensuring(_ >= 0)    
  }

  def theorem() = { 
    val n = Nat()
    n.load(-1)
    assert(n.extract() == 0)  // should be -1
  }
}
```

The second issue is that the invariant on Nat() cannot be maintained due to the `Box.load` method.

```scala
object Imperative {
  case class Container(var v: BigInt) {
    def load(x: BigInt) = {
      v = x
    }
  }

  abstract class Box {
    val c = Container(0)
    def load(x: BigInt) = c.load(x)
  }

  case class Nat() extends Box {
    require(c.v >= 0)          // should not be allowed (?)
    
    def extract(): BigInt = {
      c.v
    } ensuring(_ >= 0)       
  }

  def theorem() = { 
    val n = Nat()
    n.load(-1)
    assert(n.extract() == -1) // doesn't verify while it should
    assert(false)             // extract only returns non-negative numbers
  }
}
```

PS: Box uses a Container instead of directly a var because var's are currently not supported in abstract classes

**Comment by samarion** [comment] 2017-12-14 14:35
This issue is due to vals being extracted as methods in Stainless. The `val c: Container(0)` in `Box` is actually treated as `def c: Container(0)` so `Box.load` has no effect. The termination checker also doesn't handle `val` definitions correctly according to Scala semantics. Finally, we also don't check that the initialization order makes sense, so you could have null pointers do to these fields. For example
```scala
case class A() {
  val a = b
  val b = List(1,2,3)
}
```
would compile in Scala (I think) but throw a null-pointer exception at runtime.

The easiest way to fix this is to add a check that rejects `val` definitions in classes that have impure types. It should be possible to fix these issues (_i.e._ make Stainless compliant with Scala semantics) but it won't be trivial.

**Comment by jad-hamza** [comment] 2017-12-14 20:04
Ah I see. So we would disable `val x: T = _` anywhere when T is an impure type? Or only in classes?

Should we also explicitly disable support for `var`'s in abstract classes and traits for that example below? We would prevent mutable state altogether on any object that can be extended?

Right now the example fails due to registry errors:

> [ Error  ] theorem$0 depends on missing dependencies: v$7.
> [ Error  ] load$0 depends on missing dependencies: v_=$0.
> [ Error  ] inv$1 depends on missing dependencies: v$7.
> [Internal] Missing some nodes in Registry: v_=$0, v$7
> [Internal] Please inform the authors of Inox about this message
> [Internal] inox.package$FatalError: Missing some nodes in Registry: v_=$0, v$7
> [Internal] Please inform the authors of Inox about this message


```scala
object Imperative {
  trait Box {
    var v = BigInt(0)
    def load(x: BigInt) = {
      v = x
    }
  }

  case class Nat() extends Box {
    require(v >= 0)          // should not be allowed (?)
  }

  def theorem() = { 
    val n = Nat()
    n.load(-1)
    assert(n.v == -1)
    assert(false)             // contradiction with Nat's invariant
  }
}
```

**Comment by samarion** [comment] 2017-12-15 10:28
Yes, we should reject vars in trait and class bodies during extraction to provide clearer reporting.

Note that the issue isn't about being abstract or concrete, it's just that `val` definitions in classes/traits don't actually constitute _state_ for those objects, so they must be pure. You can still have state in your hierarchies by doing:
```scala
sealed trait Box {
  def load(x: BigInt): Unit
}

case class Nat(var v: BigInt) extends Box {
  require(v >= 0)
  def load(x: BigInt): Unit = {
    require(x >= 0)
    v = x
  }
}
```
The imperative transformation should be able to handle this definition.

It should also be possible to add a transformation that injects mutable vals in class/trait bodies into their constructor arguments which would enable support for your initial example. However, special care would have to be taken for dependencies between vals/vars in the class body during construction.

**Comment by jad-hamza** [comment] 2017-12-15 10:55
Just to clarify what you said, we will reject
```scala
abstract class Box(var v: BigInt)
```
and
```scala
abstract class Box {
  var v: BigInt
}
```
but allow
```scala
case class Box(var v: BigInt)
```
and
```scala
case class Box {
  var v: BigInt
}
```
right?

**Comment by samarion** [comment] 2017-12-15 11:00
We will also reject vars in class bodies (last example) as supporting these is similar to supporting impure vals. The only allowed syntax for mutable fieds in classes is the 3rd one.

**Comment by vkuncak** [comment] 2017-12-21 15:47
In discussion with Regis we concluded that vars that are _not_ inside the constructor parameter list are a total mess and should not exist in Scala either.

**Comment by vkuncak** [comment] 2017-12-21 15:48
By the way, we may wish to rework the entire support for imperative features in Stainless. I would prefer to treat these as syntactic sugar for their translation for now and focus on getting higher-order things correct first.

**Comment by samarion** [comment] 2018-03-20 16:44
Scalac extractor now correctly rejects everything it should (with warnings).
For dotty, it's still not quite clear whether we want the same checks. I'll close this issue for now and we can later determine which checks dotty needs.

**Comment by jad-hamza** [comment] 2018-03-27 17:04
This example from above is still throwing an internal error:

```scala
object Imperative {
  trait Box {
    var v = BigInt(0)
    def load(x: BigInt) = {
      v = x
    }
  }
}
```

```scala
[Warning ] File.scala:2:3: Consider sealing Box.
             trait Box {
             ^^^^^^^^^^^...
[ Error  ] load$0 depends on missing dependencies: v_=$0.
[Internal] Missing some nodes in Registry: v_=$0
[Internal] Please inform the authors of Inox about this message

**Comment by samarion** [comment] 2018-03-30 23:24
Fixed (really this time, I hope) in https://github.com/epfl-lara/stainless/commit/22dc9eaf97d49a97fb3ca71d75cda6caad4d2919

**Closed by samarion** 2018-03-30 23:24 UTC
Labels: reporting, soundliness
